# Generated by Django 5.1.1 on 2024-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0016_rename_installment_no_user_installment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='last_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
