# Generated by Django 5.1.1 on 2024-10-10 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0017_alter_payment_last_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='installment_number',
        ),
        migrations.AddField(
            model_name='user',
            name='account_created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
